name: Bug Report

description: Use this template to report a bug.

labels: bug

body:
  - type: markdown
    attributes:
      value: |
        ## Description
        Please provide a clear and concise description of the bug.

  - type: input
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: "Step 1, Step 2, Step 3"
      
  - type: input
    attributes:
      label: Expected Behavior
      description: Describe the behavior you expected.
      placeholder: "What did you expect to happen?"

  - type: input
    attributes:
      label: Actual Behavior
      description: Describe the behavior that actually occurred.
      placeholder: "What actually happened?"

  - type: input
    attributes:
      label: Screenshots (if applicable)
      description: Add any relevant screenshots.
      placeholder: "Screenshots or other visuals can help us understand the issue."
      
  - type: input
    attributes:
      label: Environment (optional)
      description: Add any relevant details about your environment (OS, version, etc.).
      placeholder: "Operating system version, CPU architecture, etc."
