name: Feature Request

description: Use this template to propose a new feature.

labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Description
        Please provide a clear and concise description of the feature.

  - type: input
    attributes:
      label: Motivation
      description: Why should this feature be added? What problems will it solve?
      placeholder: "Explain why this feature would be valuable."

  - type: input
    attributes:
      label: Additional Information
      description: Add any additional details or use cases for this feature.
      placeholder: "Provide further context or examples, if necessary."

  - type: input
    attributes:
      label: Alternative Solutions (if any)
      description: Describe any alternative solutions or workarounds you've considered.
      placeholder: "What other approaches have you tried or considered?"

  - type: input
    attributes:
      label: Screenshots/Mockups (if applicable)
      description: Add any relevant screenshots or mockups of the feature.
      placeholder: "Visuals or mockups can help clarify the feature."
